---
networks:
- name: compilation
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.10.0/24
    reserved:
    - 10.244.10.1
    az: z1
- name: peer
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.8.0/24
    reserved:
    - 10.244.8.1
    az: z1
  - cloud_properties: {}
    range: 10.244.9.0/24
    reserved:
    - 10.244.9.1
    az: z2
- name: ethpeer
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.11.0/24
    reserved:
    - 10.244.11.1
    az: z1
  - cloud_properties: {}
    range: 10.244.12.0/24
    reserved:
    - 10.244.12.1
    az: z2
- name: peer1
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.13.0/24
    reserved:
    - 10.244.13.1
    az: z1
  - cloud_properties: {}
    range: 10.244.14.0/24
    reserved:
    - 10.244.14.1
    az: z2
- name: peer2
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.15.0/24
    reserved:
    - 10.244.15.1
    az: z1
  - cloud_properties: {}
    range: 10.244.16.0/24
    reserved:
    - 10.244.16.1
    az: z2
- name: peer3
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.17.0/24
    reserved:
    - 10.244.17.1
    az: z1
  - cloud_properties: {}
    range: 10.244.18.0/24
    reserved:
    - 10.244.18.1
    az: z2
azs:
- name: z1
  cloud_properties: {}
- name: z2
  cloud_properties: {}
vm_types:
- name: small
  cloud_properties: {}
compilation:
  cloud_properties: {}
  network: compilation
  az: z1
  vm_type: small
  reuse_compilation_vms: true
  workers: 2
