---
name: hyperledger-fabric
director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8
stemcells:
- alias: default
  name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: latest
releases:
- name: fabric-release
  version: latest
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 3
  serial: true
  update_watch_time: 5000-120000
jobs:
- instances: 1
  azs: [z1, z2]
  name: membersrvc
  networks:
  - name: peer
  persistent_disk: 1024
  vm_type: small
  stemcell: default
  templates:
  - name: member_service
    release: fabric-release
- instances: 3
  azs: [z1, z2]
  name: peer
  networks:
  - name: peer
  persistent_disk: 1024
  vm_type: small
  stemcell: default
  templates:
  - name: peer
    release: fabric-release
  - name: docker
    release: fabric-release
- instances: 1
  azs: [z2]
  name: acceptance_test
  networks:
  - name: peer
  vm_type: small
  stemcell: default
  lifecycle: errand
  templates:
  - name: acceptance-tests
    release: fabric-release
  properties:
    acceptance_test:
      skip_deploy: false
      use_new_user: true
- instances: 1
  azs: [z2]
  name: smoke_test
  networks:
  - name: peer
  vm_type: small
  stemcell: default
  lifecycle: errand
  templates:
  - name: acceptance-tests
    release: fabric-release
  properties:
    acceptance_test:
      skip_deploy: true
      use_new_user: false
properties:
  acceptance_test:
    registrar_name: WebAppAdmin
    registrar_password: DJY27pEnl16d
    username: binhn
    password: 7avZQLwcUe9q
  peer:
    consensus:
      plugin: pbft
    security:
      enabled: true
      attributes:
        enabled: true
    core:
      data_path: /var/vcap/data/hyperledger/production
  docker:
    store:
      dir: /var/vcap/data/docker
  membersrvc:
    aca:
      enabled: true
    affiliations:
      banks_and_institutions:
        banks:
            - bank_a
            - bank_b
            - bank_c
        institutions:
            - institution_a
            - institution_b
    clients:
    - name: admin
      secret: Xurw3yU9zI0l
      affiliation: institution_a
      affiliation_role:
      metadata: '''{"registrar":{"roles":["client","peer","validator","auditor"],"delegateRoles":["client"]}}'''
    - name: WebAppAdmin
      secret: DJY27pEnl16d
      affiliation: institution_a
      affiliation_role:
      metadata: '''{"registrar":{"roles":["client"],"delegateRoles":["client"]}}'''
    - name: lukas
      secret: NPKYL39uKbkj
      affiliation: bank_a
      affiliation_role: 00001
      metadata:
    - name: system_chaincode_invoker
      secret: DRJ20pEql15a
      affiliation: institution_a
      affiliation_role: 00002
      metadata:
    - name: diego
      secret: DRJ23pEQl16a
      affiliation: institution_a
      affiliation_role: 00003
      metadata:
    - name: binhn
      secret: 7avZQLwcUe9q
      affiliation: institution_a
      affiliation_role: 00005
      metadata:
    - name: jim
      secret: 6avZQLwcUe9b
      affiliation: bank_a
      affiliation_role: 00004
      metadata:
    validators:
    - name: vp0
      secret: f3489fy98ghf
    - name: vp1
      secret: MwYpmSRjupbT
    - name: vp2
      secret: 5wgHK9qqYaPy
    - name: vp3
      secret: vQelbRvja7cJ
    non_validators:
    - name: nvp0
      secret: iywrPBDEPl0K
      affiliation: bank_a
      affiliation_role: 00006
    - name: nvp1
      secret: DcYXuRSocuqd
      affiliation: institution_a
      affiliation_role: 00007
    auditors:

